groups:
#
# DEFAULT
#
#bukkit
  g:bukkit_default:
    permissions:
    - -bukkit.command.plugins
    - bukkit.broadcast.user
    - bukkit.command.time
    - bukkit.command.time.add
    - bukkit.command.time.set
#deathchest
  g:dc_default:
    permissions:
    - deathchest.remove.own
    - deathchest.list.*
    - deathchest.giveBack
#essentials
  g:essentials_default:
    permissions:
    - essentials.help
    - essentials.helpop
    - essentials.jail.allow.help
    - essentials.jail.allow.helpop
    - essentials.jail.allow.rules
    - essentials.list
    - essentials.motd
    - essentials.rules
    - essentials.spawn
    - essentials.world
    - essentials.worlds.depressed_plungers
    - essentials.worlds.depressed_plungers_nether
#groupmanager
  g:groupmanager_default:
    permissions:
    - groupmanager.notify.self
#lwc
  g:lwc_default:
    permissions:
    - lwc.deny
    - lwc.cdisplay
#worldguard
  g:wg_default:
    permissions:
    - worldguard.locate
    - worldguard.stack
    - worldguard.region.notify.member.*
    - worldguard.region.list.member.*
    - worldguard.region.info.member.*
    - worldguard.region.load.member.*
    - worldguard.region.save.member.*
#vote
  g:vote_default:
    permissions:
    - vote.voteyes.*
    - vote.voteno.*
    - vote.startvote.*

#
# BUILDER
#
#bukkit
  #none
#essentials
  g:essentials_builder:
    permissions:
    - essentials.afk
    - essentials.afk.auto
    - essentials.back
    - essentials.back.ondeath
    - essentials.balance
    - essentials.balance.others
    - essentials.balancetop
    - essentials.book
    - essentials.build.*
    - essentials.chat.color
    - essentials.chat.format
    - essentials.chat.question
    - essentials.chat.shout
    - essentials.compass
    - essentials.delhome
    - essentials.depth
    - essentials.exp
    - essentials.getpos
    - essentials.hat
    - essentials.home
    - essentials.ignore
    - essentials.itemdb
    - essentials.jail.allow.mail
    - essentials.jail.allow.ping
    - essentials.jail.allow.seen
    - essentials.kit
    - essentials.kits.tools
    - essentials.mail
    - essentials.mail.send
    - essentials.me
    - essentials.msg
    - essentials.msg.color
    - essentials.msg.format
    - essentials.nick
    - essentials.pay
    - essentials.ping
    - essentials.powertool
    - essentials.powertooltoggle
    - essentials.protect
    - essentials.recipe
    - essentials.seen
    - essentials.sell
    - essentials.sell.*
    - essentials.sethome
    - essentials.sethome.bed
    - essentials.sethome.multiple
    - essentials.signs.break.disposal
    - essentials.signs.break.mail
    - essentials.signs.break.protection
    - essentials.signs.break.time
    - essentials.signs.break.trade
    - essentials.signs.break.weather
    - essentials.signs.create.disposal
    - essentials.signs.create.mail
    - essentials.signs.create.protection
    - essentials.signs.create.time
    - essentials.signs.create.trade
    - essentials.signs.create.weather
    - essentials.signs.use.*
    - essentials.suicide
    - essentials.time
    - essentials.time.set
    - essentials.tpa
    - essentials.tpaccept
    - essentials.tpahere
    - essentials.tpdeny
    - essentials.warp
    - essentials.warp.list
    - essentials.weather
    - essentials.worth
#groupmanager
  #none
#lwc
  g:lwc_builder:
    permissions:
    - lwc.protect
    - lwctrust.trust

#worldguard
  g:wg_builder:
    permissions:
    - worldguard.region.notify.own.*
    - worldguard.region.info.own.*
    - worldguard.region.load.own.*
    - worldguard.region.save.own.*
    - worldguard.region.claim
    - worldguard.region.redefine.own.*
    - worldguard.region.addmember.own.*
    - worldguard.region.addowner.own.*
    - worldguard.region.removemember.own.*
    - worldguard.region.flag.regions.own.*
    - worldguard.region.flag.flags.use.* #doors & levers
    - worldguard.region.flag.flags.pvp.* #pvp
    - worldguard.region.flag.flags.passthrough.* #building
    - worldguard.region.flag.flags.tnt.* #tnt explosions
    - worldguard.region.flag.flags.deny-spawn.* #stop certain mobs spwaning
    - worldguard.region.flag.flags.mob-spawning.* #stop mobs from spawning
    - worldguard.region.flag.flags.notify-enter.* #notify when people enter
    - worldguard.region.flag.flags.notify-leave.* #notify when people leave
    - worldguard.region.flag.flags.greeting-title.* #set title for region

#
# MODERATOR
#
#bukkit
  g:bukkit_moderator:
    permissions:
    - bukkit.command.kick
    - bukkit.command.unban
    - bukkit.command.unban.ip
    - bukkit.command.unban.player
    - bukkit.command.whitelist
    - bukkit.command.whitelist.add
    - bukkit.command.whitelist.disable
    - bukkit.command.whitelist.enable
    - bukkit.command.whitelist.list
    - bukkit.command.whitelist.reload
    - bukkit.command.whitelist.remove
#essentials
  g:essentials_moderator:
    permissions:
    - essentials.afk.kickexempt
    - essentials.tempban
    - essentials.book.others
    - essentials.book.title
    - essentials.broadcast
    - essentials.chat.magic
    - essentials.chat.url
    - essentials.clearinventory
    - essentials.delwarp
    - essentials.eco.loan
    - essentials.exp.others
    - essentials.ext
    - essentials.fly
    - essentials.fly.safelogin
    - essentials.getpos
    - essentials.getpos.others
    - essentials.helpop.receive
    - essentials.home.others
    - essentials.invsee
    - essentials.jail.allow.jails
    - essentials.jail.allow.togglejail
    - essentials.jails
    - essentials.jump
    - essentials.kick
    - essentials.kick.notify
    - essentials.kill
    - essentials.msg.magic
    - essentials.mute
    - essentials.mute.notify
    - essentials.nick.color
    - essentials.nick.others
    - essentials.protect.admin
    - essentials.protect.alerts
    - essentials.protect.ownerinfo
    - essentials.ptime
    - essentials.ptime.others
    - essentials.realname
    - essentials.seen.banreason
    - essentials.seen.extra
    - essentials.setwarp
    - essentials.thunder
    - essentials.togglejail
    - essentials.top
    - essentials.tp
    - essentials.tp.others
    - essentials.tphere
    - essentials.tppos
    - essentials.tptoggle
    - essentials.unban
    - essentials.unbanip
    - essentials.vanish
    - essentials.vanish.effect
    - essentials.warps.*
    - essentials.whois
    - essentials.workbench
    - essentials.worlds.depressed_plungers_the_end
    - essentials.sethome.multiple.staff
#groupmanager
  g:groupmanager_moderator:
    permissions:
    - groupmanager.listgroups
    - groupmanager.mandemote
    - groupmanager.manpromote
    - groupmanager.manselect
    - groupmanager.manuadd
    - groupmanager.manudel
    - groupmanager.manwhois
    - groupmanager.notify.other
#lwc
  g:lwc_moderator:
    permissions:
    - lwc.mod
    - lwc.shownotices
    - lwc.history
    - lwc.details
#worldguard
  g:wg_moderator:
    permissions:
    - worldguard.region.addmember.*
    - worldguard.region.removemember.*
    - worldguard.region.staff
#vanish
  g:vanish_moderator:
    permissions:
    - sv.keepfly
    - sv.login
    - sv.logout
    - sv.see.1
    - sv.toggleitems
    - sv.use.1
    - vanish.hooks.essentials.hide
#vote
  g:vote_moderator:
    permissions:
    - vote.unkickable
    - vote.veto





#
# ADMIN
#
#
#bukkit
  g:bukkit_admin:
    permissions:
    - bukkit.command.ban
    - bukkit.command.ban.ip
    - bukkit.command.ban.player
    - -bukkit.command.op
    - -bukkit.command.op.give
    - -bukkit.command.op.take
    - bukkit.broadcast
    - bukkit.broadcast.admin
    - bukkit.command.gamemode
    - bukkit.command.give
    - bukkit.command.help
    - bukkit.command.kill
    - bukkit.command.list
    - bukkit.command.me
    - bukkit.command.plugins
    - bukkit.command.reload
    - bukkit.command.save
    - bukkit.command.save.disable
    - bukkit.command.save.enable
    - bukkit.command.save.perform
    - bukkit.command.say
    - bukkit.command.stop
    - bukkit.command.teleport
    - bukkit.command.tell
    - bukkit.command.version
#deathchest
  g:dc_admin:
    permissions:
    - deathchest.remove.other
    - deathchest.admin
#essentials
  g:essentials_admin:
    permissions:
    - -essentials.spawner.enderdragon
    - -essentials.backup
    - -essentials.essentials
    - -essentials.setspawn
    - -essentials.reloadall
    - -essentials.plugin
    - essentials.*
    - essentials.ban
    - essentials.ban.notify
    - essentials.banip
    - essentials.kick.exempt
    - essentials.ban.exempt
    - essentials.signs.break.*
    - essentials.signs.create.*
    - essentials.spawner
    - essentials.spawner.*
#groupmanager
  g:groupmanager_admin:
    permissions:
    - groupmanager.mangcheckp
    - groupmanager.manglistp
    - groupmanager.mansave
    - groupmanager.mantogglevalidate
    - groupmanager.manucheckp
    - groupmanager.manulistp
#lwc
  g:lwc_admin:
    permissions:
    - lwc.admin.view
    - lwc.admin.find
    - lwc.admin.forceowner
    - lwc.admin.remove
    - lwc.admin.purge
    - lwc.admin.cleanup
    - lwc.admin.update
    - lwc.admin.report
#worldguard
  g:wg_admin:
    permissions:
    - worldguard.reload
    - worldguard.region.wand
    - worldguard.region.define
    - worldguard.region.unlimited
    - worldguard.region.list.*
    - worldguard.region.remove.*
    - worldguard.region.addowner.*
    - worldguard.region.addmember.*
    - worldguard.region.removemember.*
    - worldguard.region.removeowner.*
    - worldguard.region.setpriority.*
    - worldguard.region.setparent.*
    - worldguard.region.flag.*
#vanish
  g:vanish_admin:
    permissions:
    - sv.list
    - sv.notoggle
    - sv.others
    - sv.recreatefiles
    - sv.reload
    - sv.see.2
    - sv.use.2
#vote
  g:vote_admin:
    permissions:
    - vote.setvalue
    - vote.reload
    - vote.unbannable
